"""Initial migration

Revision ID: 90d8d4e8756e
Revises: 
Create Date: 2025-08-04 10:35:13.766860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d8d4e8756e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('sender_phone', sa.String(length=20), nullable=False),
    sa.Column('receiver_name', sa.String(length=120), nullable=False),
    sa.Column('receiver_phone', sa.String(length=20), nullable=False),
    sa.Column('pickup_address', sa.String(length=255), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('eco_mode', sa.Boolean(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('delivery_time', sa.String(length=50), nullable=True),
    sa.Column('qr_code_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('courier_name', sa.String(length=100), nullable=True),
    sa.Column('estimated_delivery', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcels')
    op.drop_table('users')
    # ### end Alembic commands ###
